<?php require 'header.php'; ?>
<?php require 'menu.php' ?>
<?php require 'banner.php' ?>
<?php require 'touch.php' ?>
<?php require 'about.php' ?>
<?php require 'service.php' ?>
<?php require 'testimonial.php' ?>
<?php require 'contact.php'; ?>
<?php require 'footer.php'; ?>